[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
strike = "73aZc4WACFdJ288yQmEq9RsGS3neC3P3keqGXmGktVh7"

[programs.devnet]
strike = "73aZc4WACFdJ288yQmEq9RsGS3neC3P3keqGXmGktVh7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
